### ISSUE TITLE
Migration from zeebe 8.5 to 8.6

### ISSUE THREAD

**Issue by emaarco** [camunda/zeebe-process-test#1268]
Hello everyone 👋 

I have a Spring service that uses Zeebe for process orchestration. Currently, I'm using version 8.5 of the Zeebe client along with its Spring dependencies. I'm looking to upgrade to version 8.6 of the Zeebe client and am running into some confusion with the migration steps.

**Here's my situation:**
I see that I need to migrate from io.camunda.spring:spring-boot-starter-camunda ([link](https://mvnrepository.com/artifact/io.camunda.spring/spring-boot-starter-camunda)) to io.camunda:spring-boot-starter-camunda-sdk ([link](https://mvnrepository.com/artifact/io.camunda/spring-boot-starter-camunda-sdk/8.6.5))

**In context to this repo**
Additionally, I wanted to update the testing dependencies. Specifically, I was using io.camunda.spring:spring-boot-starter-camunda-test ([link](https://mvnrepository.com/artifact/io.camunda.spring/spring-boot-starter-camunda-test/8.5.14)) - because some of my process-tests require spring-support. 

However, I can't find a version for 8.6, nor could i find a migration note, telling me that i need to migrate here as well. It seems like 8.6 is only available for zeebe-process-test ([link](https://mvnrepository.com/artifact/io.camunda/zeebe-process-test-extension/8.6.5)) But in your documentation, there's a note suggesting that if I want to use it in Spring, I also need to add spring-zeebe-test as a wrapper.

This leaves me unsure about how to proceed with the migration. My questions are:
- Is there any migration guide I may have missed?
- Is the note about using spring-zeebe-test as a wrapper still valid for 8.6 (does it need to be changed)?

Thanks in advance! :)

**Comment by emaarco** [comment]
closed

**Comment by emaarco** [comment]
I must be blind somehow :person_shrugging:
I've missed the note:

> Heads up! We are building a new Java testing library for Camunda 8.6+. The new library will replace Zeebe Process Test eventually. New features: Access to Camunda’s new REST API, official Spring integration, process coverage, improved UX, and more ([ref](https://github.com/camunda/issues/issues/751)). Stay tuned for updates. :rocket:

Can I assume from this that I can’t meaningfully migrate to 8.6 until this library is available? Is there a plan for when this might be? Based on the link its potential:8.8.

**Comment by saig0** [comment]
> Can I assume from this that I can’t meaningfully migrate to 8.6 until this library is available? 

Yes, ZPT doesn't have an integration for the Spring SDK. You could still use ZPT with your Spring application but not fully integrated in the Spring test lifecycle. 

> Is there a plan for when this might be? Based on the link its potential:8.8.

The new library Camunda Process Test (CPT) is available in an alpha version. You can try it out following the documentation: 
https://docs.camunda.io/docs/apis-tools/testing/getting-started/.

**Comment by emaarco** [comment]
Hi @saig0 - yes. this is what i've tried (to use the plain-library).
However, some of our tests, are implemented in a way that the require specific spring-support. 
So fully migrating to this library, would have caused some effort.

Thank you for linking the documentation to the new library (in alpha).

Do you think it could be useful to also add this note to the readme of the repo?
I think a main cause for my confusion was also this comment which references to the old library 
(that has neither a version 8.6 nor a link to a successor on mvnrepo)

> NOTE: If you use Spring and want to write tests, please use spring-zeebe-test as a wrapper around Zeebe Process Test to hook everything into the Spring lifecycle. See [Spring Zeebe: Writing test cases](https://github.com/camunda-community-hub/spring-zeebe#writing-test-cases) for details.

**Comment by saig0** [comment]
@emaarco good point. I'll update the note.
