### ISSUE TITLE
Modify EngineStateMonitor to use built-in Zeebe functionality

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe-process-test#133]
**Description**

In https://github.com/camunda-cloud/zeebe/pull/8510 a mechanism was introduced in Zeebe which can be used to track if 
processing has reached the end. We should use this instead of our own implementation in the `EngineStateMonitor` to check if the engine is idle.

**Comment by remcowesterhoud** [comment]
@pihme If you'd like it'd be cool if you could revisit the `EngineStateMonitor`

**Comment by pihme** [comment]
Removed myself from assignee, as I haven't been working on it in the last few weeks and unclear if and when I will continue
