### ISSUE TITLE
Examples are hard to understand

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/zeebe-process-test#367]
**Description**

All examples just extend an abstract class with the test implementation. 

As a new user looking for examples it's quite difficult to understand, especially if you look up the code on github directly in your browser.

Easy examples without full featured DRY would be much better to learn from.

**Comment by saig0** [comment]
Good point 👍  Let's add some pure samples for users as part of the repository. We should include the tests in the build pipeline to ensure that the samples are working.

**Comment by pihme** [comment]
@ingorichtsmeier If you find the time, feel free to add your two cents to #399. 

It is based on an example we already had, but which got a bit buried in all the files. I hope this is more helpful. Still needs a bit of polish, though. 

The other tests will probably stay as they are, but we won't advertise them as examples anymore.
