### ISSUE TITLE
Disable environment variable overrides for ZeebeClient of test engines

### ISSUE THREAD

**Issue by berndruecker** [camunda/zeebe-process-test#375]
Context: https://github.com/camunda-community-hub/spring-zeebe/issues/199

The ZeebeClient just introduced a flag to disable environment variable overrides: https://github.com/camunda-community-hub/spring-zeebe/issues/199https://github.com/camunda/zeebe/issues/9401 which now needs to be used within zeebe-process-test (as ZeebeClient's for TestEngines should never use any config from environment variables).

I will provide a PR based on Zeebe-cliebnt-java 8.1.0-SNAPSHOT

**Comment by berndruecker** [comment]
Created PR: https://github.com/camunda/zeebe-process-test/pull/376

**Comment by remcowesterhoud** [comment]
I'll make sure it is included, thanks! 👍
