### ISSUE TITLE
Gradle: Cannot find Agrona dependency using spring-zeebe-test 

### ISSUE THREAD

**Issue by tomaspizarro15** [camunda/zeebe-process-test#380]
Hello Guys , sorry to bother. I been trying to setup a Camunda 8 Zeebe project on a Spring Rest API (gradle spring project) everything about the main features of the library work okey (zeebeClient and workers) but...

Same issue in camunda-community repositories: https://github.com/camunda-community-hub/camunda-8-examples/issues/2

My issue started when I started using "spring-zeebe-test" dependency and @ZeebeTest , the error itself:

Could not resolve org.agrona:agrona:{strictly [1.14,1.15[; prefer 1.15.0}. Required by: project : > io.camunda:spring-zeebe-test:8.0.2
camunda-zeebe version: 8.0.4 (also tried 8.0.2 , and 8.0.0)

gradle repository: mavenCentral

![image](https://user-images.githubusercontent.com/61084368/170552088-3e742984-965a-4a16-9e0d-6495b97be43d.png)

Spring 2.7.0 and tried 2.6.7
Java Open JDK 17

If you have any clue of what could be happening , that will be great , thanks for your time!

**Comment by remcowesterhoud** [comment]
Thanks for reaching out @tomaspizarro15 

Could you maybe provide me with your dependency graph? Is there any chance you are using a different version of agrona in your own project?

**Comment by tomaspizarro15** [comment]
Thanks to you.  Agrona was imported only by the use of spring-zeebe-test. Im searching out how to share to you the dependency map.

but I share to you a code-snipped with the dependencies I got

This is the gradle settings configuration: 

`rootProject.name = 'prepurchase'
enableFeaturePreview('VERSION_CATALOGS')

dependencyResolutionManagement {
    versionCatalogs{
        libs {
            // Spring-boot
            library( "spring-boot-starter-web","org.springframework.boot:spring-boot-starter-web:${springBootVersion}")
            library("logstash-logback-encoder", "net.logstash.logback:logstash-logback-encoder:${logstashLogbackEncoderVersion}")
            bundle('spring-boot', ['spring-boot-starter-web','logstash-logback-encoder'])
               // Lombok
            library('lombok', "org.projectlombok:lombok:${lombokVersion}")
            // Camunda/Zeebe
            library('spring-zeebe-starter', "io.camunda:spring-zeebe-starter:${zeebeVersion}")
            library('zeebe-test-extenstion' , "io.camunda:zeebe-process-test-extension:${zeebeVersion}")
            library('spring-zeebe-test' , "io.camunda:spring-zeebe-test:${zeebeVersion}")
            bundle('spring-zeebe' , ['spring-zeebe-starter' ,'spring-zeebe-test'])
            // Test
            library('spring-boot-starter-test', "org.springframework.boot:spring-boot-starter-test:${springBootVersion}")
            bundle('test-libs', ['spring-boot-starter-test' ])
            // Others

        }
    }
}
`



AND...

Full log of the error 
`Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve org.agrona:agrona:1.15.0.
     Required by:
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0 > io.camunda:zeebe-workflow-engine:8.0.0
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0 > io.camunda:zeebe-util:8.0.0
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0 > io.camunda:zeebe-logstreams:8.0.0
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0 > io.camunda:zeebe-msgpack-value:8.0.0
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0 > io.camunda:zeebe-protocol:8.0.0
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0 > io.camunda:zeebe-protocol-impl:8.0.0
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0 > io.camunda:zeebe-db:8.0.0
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0 > io.camunda:zeebe-workflow-engine:8.0.0 > io.camunda:zeebe-msgpack-core:8.0.0
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0 > io.camunda:zeebe-workflow-engine:8.0.0 > io.camunda:zeebe-expression-language:8.0.0
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0 > io.camunda:zeebe-workflow-engine:8.0.0 > io.camunda:zeebe-dmn:8.0.0
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0 > io.camunda:zeebe-logstreams:8.0.0 > io.camunda:zeebe-dispatcher:8.0.0
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0 > io.camunda:zeebe-logstreams:8.0.0 > io.camunda:zeebe-atomix-cluster:8.0.0
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0 > io.camunda:zeebe-workflow-engine:8.0.0 > io.camunda:zeebe-expression-language:8.0.0 > io.camunda:zeebe-feel-integration:8.0.0
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0 > io.camunda:zeebe-logstreams:8.0.0 > io.camunda:zeebe-atomix-cluster:8.0.0 > io.camunda:zeebe-snapshots:8.0.0
         project : > io.camunda:spring-zeebe-test:8.0.2 > io.camunda:zeebe-process-test-extension:8.0.0 > io.camunda:zeebe-process-test-engine:8.0.0 > io.camunda:zeebe-logstreams:8.0.0 > io.camunda:zeebe-atomix-cluster:8.0.0 > io.camunda:zeebe-journal:8.0.0
      > Cannot find a version of 'org.agrona:agrona' that satisfies the version constraints:
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-workflow-engine:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-util:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-logstreams:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-msgpack-value:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-protocol:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-protocol-impl:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-db:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-workflow-engine:8.0.0' (compile) --> 'io.camunda:zeebe-msgpack-core:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-workflow-engine:8.0.0' (compile) --> 'io.camunda:zeebe-expression-language:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-workflow-engine:8.0.0' (compile) --> 'io.camunda:zeebe-dmn:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-workflow-engine:8.0.0' (compile) --> 'uk.co.real-logic:sbe-tool:1.25.2' (apiElements) --> 'org.agrona:agrona:{strictly [1.14,1.15[; prefer 1.15.0}'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-logstreams:8.0.0' (compile) --> 'io.camunda:zeebe-dispatcher:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-logstreams:8.0.0' (compile) --> 'io.camunda:zeebe-atomix-cluster:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-workflow-engine:8.0.0' (compile) --> 'io.camunda:zeebe-expression-language:8.0.0' (compile) --> 'io.camunda:zeebe-feel-integration:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-logstreams:8.0.0' (compile) --> 'io.camunda:zeebe-atomix-cluster:8.0.0' (compile) --> 'io.camunda:zeebe-snapshots:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'
           Dependency path 'com.kavak.processes:prepurchase:0.0.1-SNAPSHOT' --> 'io.camunda:spring-zeebe-test:8.0.2' (compile) --> 'io.camunda:zeebe-process-test-extension:8.0.0' (compile) --> 'io.camunda:zeebe-process-test-engine:8.0.0' (compile) --> 'io.camunda:zeebe-logstreams:8.0.0' (compile) --> 'io.camunda:zeebe-atomix-cluster:8.0.0' (compile) --> 'io.camunda:zeebe-journal:8.0.0' (compile) --> 'org.agrona:agrona:1.15.0'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

`

**Comment by remcowesterhoud** [comment]
I'm a bit confused about the version range defined by `sbe-tool`. [Their code says it allows any agrona patch versions of 1.14](https://github.com/real-logic/simple-binary-encoding/blob/1.25.2/build.gradle#L51). Yet the error here says it prefers 1.15.0. With `spring-zeebe-test` we pull in 1.15.0. With Maven this is working fine, but with Gralde I can easily reproduce the issue:

```
dependencies {
    implementation 'org.agrona:agrona:1.15.0'
    implementation 'uk.co.real-logic:sbe-tool:1.25.2'
}
```

**Comment by tomaspizarro15** [comment]
Hi @remcowesterhoud  , Sorry two return here after so much time , Some news about the bug with Agrona versioning in Gradle implementation?

**Comment by remcowesterhoud** [comment]
Hi @tomaspizarro15. Thanks for the reminder about this issue and sorry for taking so long to get back at you.

I did some digging on the differences between Maven and Gradle. The issue here is caused by the way both tools handle they dependency resolution. Maven uses a nearest-first strategy. It will take the shortest path to a dependency and use that version.
Gradle will analyse all the requested versions and will select the highest version. If this version is different from the version Maven found, it can cause issues like this one where it works fine on Maven, but not on Gradle.
You can read more about this dependency resolution here: https://docs.gradle.org/current/userguide/dependency_resolution.html

Since `sbe-tool` strictly does not want to use version > 1.14 it will fail the build. You'll have to tell Gradle how to resolve this issue. You can configure it to force a specific version of Agrona. I would propose you force downgrade it to 1.14.0, as `sbe-tool` explicitly doesn't want to use a higher version. You can do this by adding this to you build file:
```
configurations.all {
    resolutionStrategy {
        force 'org.agrona:agrona:1.15.0', 'org.agrona:agrona:1.14.0'
    }
}
```
This will force the dependency resolution of Agrona to use 1.14.0 when it finds 1.15.0.

Please let me know if you encounter any more issues.

**Comment by tomaspizarro15** [comment]
Thanks a lot for answering , I ll try to implement this solution!
