### ISSUE TITLE
Support the process instance modification command

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe-process-test#466]
## Description

With Zeebe `8.1.0`, we added a new process instance modification API. We should support the new command also in ZPT.

- Map the request to a command in the `GrpcToLogStreamGateway` and write it
- Map the response in the `GrpcResponseMapper`

**Comment by remcowesterhoud** [comment]
Note: a lot of work for this has already been done as it blocked the alpha release https://github.com/camunda/zeebe-process-test/pull/461

Tests definitely still need to be added.
