### ISSUE TITLE
Extend the record logger for the modification command

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe-process-test#467]
**Description**

With Zeebe `8.1.0`, we added a new process instance modification record. We should extend the `RecordStreamLogger` for the new record to print only the summary of the record.

Related to https://github.com/camunda/zeebe/issues/9993

**Comment by remcowesterhoud** [comment]
Note: a lot (if not all) of work for this has already been done as it blocked the alpha release https://github.com/camunda/zeebe-process-test/pull/461

**Comment by saig0** [comment]
@remcowesterhoud awesome :rocket: 

The [RecordStreamLogger](https://github.com/camunda/zeebe-process-test/blob/main/filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java#L288-L296) is already updated :+1: 

So, nothing more to do :sweat_smile:
