### ISSUE TITLE
@ZeebeProcessTest and injection is ignored when placed on a super class

### ISSUE THREAD

**Issue by namero999** [camunda/zeebe-process-test#604]
There's a lot of boilerplate when it comes to activating and completing jobs. It would be ideal to place those common methods in a super class, annotated as ZeebeProcessTest and with client/engine field injection. However, in this case no field gets injected.

```java
@ZeebeProcessTest
public abstract class AbstractZeebeTest {

  protected ZeebeTestEngine engine;
  protected ZeebeClient client;

  @SneakyThrows
  public void waitForIdleState() {
    engine.waitForIdleState(ofSeconds(1));
  }

}
```

```java
public class PlanTest extends AbstractZeebeTest {

  @Test
  public void planTest() {
    waitForIdleState(); // engine will be null
  }

}
```

It would be great if this worked.

**Comment by remcowesterhoud** [comment]
Thanks for reporting @namero999. I've created a PR for it, so if all goed well this should become possible with the 8.2.0 release. This should be released somewhere around April 2023.

**Comment by namero999** [comment]
Thank you very much for the prompt feedback!

Since you mentioned the 8.2 release in April, I thought this fix was dependent on platform features. But by checking on the PR, it doesn't seem the case.

Would it be possible to push a minor version bump of the zeebe-process-test library with this improvement before April?

**Comment by remcowesterhoud** [comment]
We want to keep the versioning of this project and Zeebe aligned. As a result creating a minor release for here would mean we have to do a minor bump for the entire platform.

What I can do is make it part of the next patch release, which should be in January. A new feature shouldn't be part of a patch release, but I feel like this is a gray area between being a bug and feature.

**Comment by namero999** [comment]
Understood. Yes, I've mean patch bump, sorry.

As you point out, it's not a bug per se, but quite a surprising behaviour so maybe worth a release. If that is possible, it would be great. Looking forward to factor out lots of utils code :)
