### ISSUE TITLE
I as a zeebe-process-test user can't use `io.camunda.zeebe.process.test.engine.InMemoryEngine` class

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe-process-test#645]
**Description**

I have this class:

```java
public class ZeebeTestEngineProxy<T extends ZeebeTestEngine> extends AbstractInvocationHandler {

   private T delegate;

   public void swapZeebeEngine(T client) {
     this.delegate = client;
   }

   public void removeZeebeEngine() {
   this.delegate = null;
 }

   public T getCurrentEngine() {
     return delegate;
   }
// Other lines
}
```

 I can parameterize this instance with `io.camunda.zeebe.process.test.extension.testcontainer.ContainerizedEngine` because it has public visibility, but I can't parameterize it with `io.camunda.zeebe.process.test.engine.InMemoryEngine` because it has package-private visibility. But as I can see [the constructor](https://github.com/camunda/zeebe-process-test/blob/976fb773d331f8483f8cd272b247c3eff519598b/engine/src/main/java/io/camunda/zeebe/process/test/engine/ InMemoryEngine.java#L43) in `io.camunda.zeebe.process.test.engine.InMemoryEngine` is public.

**Comment by remcowesterhoud** [comment]
Thanks for reporting @aivinog1, do you want to create a PR to fix this?

**Comment by aivinog1** [comment]
> Thanks for reporting @aivinog1, do you want to create a PR to fix this?

Sure, I'll provide it soon :)
