### ISSUE TITLE
I as a Zeebe test creator cannot test the `ActivateJobs` RPC with the `fetchVariable` parameter

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe-process-test#675]
## Description

It seems that this parameter isn't supported in the gateway service (we are looking for `request.getFetchVariableList()`):  https://github.com/camunda/zeebe-process-test/blob/4eb3edafd8fdcdbe11e23cd2722480299fbb1b9d/engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java#L103-L123 .

So, when I call this method all variables are fetched back.

### Expected behaviour

When I call the the `ActivateJobs` RPC with the `fetchVariable` parameter, jobs that return contain only specified variables.

## Reproduction steps

<details>
<summary>Test code</summary>

```kotlin
        zeebeClient
            .newActivateJobsCommand()
            .jobType("some-type")
            .maxJobsToActivate(3)
            .fetchVariables(listOf("one", "two"))
            .send()
            .join()
```

</details>

<details>
<summary>Process</summary>

```xml
```

</details>

## Environment

- OS: MacOS 12.6.3 
- Version:  8.1.8 in Docker.

**Comment by korthout** [comment]
@aivinog1 Thank you for reporting this. This seems like something that should be fixed. We're marking it as `later` priority, as we will be focusing on other topics at the moment.
