### ISSUE TITLE
Ability to configure a custom Jackson Mapper

### ISSUE THREAD

**Issue by namero999** [camunda/zeebe-process-test#724]
Hello, when using the production ZeebeClient with Spring, it's possible to configure a custom Jackson mapper by exposing a bean named `zeebeObjectMapper`. Here for instance I can pass my own mapper configured with the JSR-310 module to serialize java.time objects.

When using the test client provided by this library however, I can't find a way to override the mapper, so the tests are failing if I try to serialize java.time objects.

Is there a way to configure the mapper at test startup?

**Comment by remcowesterhoud** [comment]
Thanks for raising this @namero999! I can think of a hacky way to do this, which is by creating the client manually:

```java
      final ObjectMapper objectMapper = new ObjectMapper();
      objectMapper.registerModule(new JSR310Module());
      client =
          ZeebeClient.newClientBuilder()
              .applyEnvironmentVariableOverrides(false)
              .gatewayAddress(client.getConfiguration().getGatewayAddress())
              .usePlaintext()
              .withJsonMapper(new ZeebeObjectMapper(objectMapper))
              .build();
```

Now this is pretty limited as it means you'll be able to serialise the variables, but deserialisation won't use this `ObjectMapper` and will still break. There is no other way to configure this at this time, unfortunately.

**Comment by remcowesterhoud** [comment]
By the way, it's also possible to use [spring-zeebe-test](https://github.com/camunda-community-hub/spring-zeebe#writing-test-cases). I'm not entirely sure, but you might be able to override the mapper when using this by providing a bean. Looking at the source code of the extension they have there they are getting this bean and setting the json mapper in the client:

```java
  public ZeebeClient createClient(TestContext testContext, ZeebeTestEngine zeebeEngine) {
    // Maybe use more of the normal config properties (https://github.com/camunda-community-hub/spring-zeebe/blob/11966be454cc76f3966fb2c0e4114a35487946fc/client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.java#L30)?
    ZeebeClientBuilder builder = ZeebeClient.newClientBuilder()
      .gatewayAddress(zeebeEngine.getGatewayAddress()).usePlaintext();
    if (testContext.getApplicationContext().getBeanNamesForType(JsonMapper.class).length>0) {
      JsonMapper jsonMapper = testContext.getApplicationContext().getBean(JsonMapper.class);
      builder.withJsonMapper(jsonMapper);
    }
    builder.applyEnvironmentVariableOverrides(false);
    return builder.build();
  }
```

**Comment by namero999** [comment]
I will take a look at spring-zeebe-test.

In the context of zeebe-process-test, probably the issue will need to be resolved around here https://github.com/camunda/zeebe-process-test/blob/main/engine/src/main/java/io/camunda/zeebe/process/test/engine/InMemoryEngine.java#L97 where the in-memory client is created with no means of overriding the mapper.

I'm not sure if zeebe-process-test is aware of the spring context, I doubt it. Given that the in-memory client is initialized when the annotation `@ZeebeProcessTest` is present on the test, maybe something can be done there, such as accepting a class for the custom mapper...

**Comment by korthout** [comment]
ZPA triage:
- there are workarounds available
- we think it could be valuable to provide a way to configure zeebe-process-test
- current priority is `later`, we may increase this if more users ask for it
- @remcowesterhoud could you provide a way forward for this issue? marking it as `upcoming` so you have some time for it soon
