### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported class file major version 64

### ISSUE THREAD

**Issue by anthraxn8b** [camunda/zeebe-process-test#859]
**Description**

I use:

java --version
openjdk 20 2023-03-21
OpenJDK Runtime Environment (build 20+36-2344)
OpenJDK 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)

mvn --version 
Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)
Maven home: /opt/homebrew/Cellar/maven/3.9.4/libexec
Java version: 20.0.1, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/20.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "13.4.1", arch: "aarch64", family: "mac"

Executing maven tests outputs (How do I upload the full stacktrace?)

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
java.lang.instrument.IllegalClassFormatException: Error while instrumenting XXX/XXX/camunda/demo/one/AbstractProcessTest with JaCoCo 0.8.8.202204050719/5dcf34a.
	at org.jacoco.agent.rt.internal_b6258fc.CoverageTransformer.transform(CoverageTransformer.java:94)
	...
	at org.jacoco.agent.rt.internal_b6258fc.CoverageTransformer.transform(CoverageTransformer.java:92)
	... 20 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 64
	at org.jacoco.agent.rt.internal_b6258fc.asm.ClassReader.<init>(ClassReader.java:199)
	...
	at org.jacoco.agent.rt.internal_b6258fc.core.instr.Instrumenter.instrument(Instrumenter.java:109)
	... 21 more
...
```

**Comment by remcowesterhoud** [comment]
Hi @anthraxn8b! The message I see you are using JDK20 and JaCoCo 0.8.8. Looking at [JaCoCo's change history](https://www.jacoco.org/jacoco/trunk/doc/changes.html) I can see it added support for java 19 and 20 in version 0.8.9.
I'd recommend you either use a jdk <19, or upgrade your JaCoCo version.

I'll be closing this issue now. Feel free to add comments/reopen if you have further comments.

**Comment by remcowesterhoud** [comment]
> The Jacoco version is coming from you (parent). ;-)

Yes sorry about that 😄 I have upgraded it now so it should be fixed in the upcoming release
