### ISSUE TITLE
Support using MigrateProcessInstance RPC

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe-process-test#972]
## Description

With https://github.com/camunda/zeebe/issues/15119 we have added a new `MigrateProcessInstance` RPC to the gRPC protocol. We must define this endpoint in the ZPT engine.

- [ ] Implement the RPC in the `GrpcToLogStreamGateway`
    - [ ] Add a response mapper to the `GrpcResponseMapper`

Would be nice to add a test case that shows that we can migrate a process instance in ZPT and then continue the process instance in the new model.

Blocked by
- https://github.com/camunda/zeebe/issues/15119

**Comment by abbasadel** [comment]
This is nice to deliver in 8.4 but not a blocker for the release
